// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/webpanel/config.proto

package webpanel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listen        string                 `protobuf:"bytes,1,opt,name=listen,proto3" json:"listen,omitempty"`
	ApiEndpoint   string                 `protobuf:"bytes,2,opt,name=api_endpoint,json=apiEndpoint,proto3" json:"api_endpoint,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	JwtSecret     string                 `protobuf:"bytes,5,opt,name=jwt_secret,json=jwtSecret,proto3" json:"jwt_secret,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,6,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	CertFile      string                 `protobuf:"bytes,7,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,8,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_webpanel_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_webpanel_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*Config) Descriptor() ([]byte, []int) {
	return file_app_webpanel_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *Config) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *Config) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Config) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Config) GetJwtSecret() string {
	if x != nil {
		return x.JwtSecret
	}
	return ""
}

func (x *Config) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *Config) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *Config) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

var File_app_webpanel_config_proto protoreflect.FileDescriptor

const file_app_webpanel_config_proto_rawDesc = "" +
	"\x0a\x19app/webpanel/c" +
	"onfig.proto\x12\x11xra" +
	"y.app.webpanel\x22\xf3" +
	"\x01\x0a\x06Config\x12\x16\x0a\x06lis" +
	"ten\x18\x01 \x01(\x09R\x06liste" +
	"n\x12!\x0a\x0capi_endpoin" +
	"t\x18\x02 \x01(\x09R\x0bapiEndp" +
	"oint\x12\x1a\x0a\x08username" +
	"\x18\x03 \x01(\x09R\x08username" +
	"\x12\x1a\x0a\x08password\x18\x04 \x01" +
	"(\x09R\x08password\x12\x1d\x0a\x0a" +
	"jwt_secret\x18\x05 \x01(\x09" +
	"R\x09jwtSecret\x12\x1f\x0a\x0bc" +
	"onfig_path\x18\x06 \x01(\x09" +
	"R\x0aconfigPath\x12\x1b\x0a\x09" +
	"cert_file\x18\x07 \x01(\x09R" +
	"\x08certFile\x12\x19\x0a\x08key" +
	"_file\x18\x08 \x01(\x09R\x07key" +
	"FileBU\x0a\x15com.xray" +
	".app.webpanelP\x01Z" +
	"&github.com/xtls" +
	"/xray-core/app/w" +
	"ebpanel\xaa\x02\x11Xray.A" +
	"pp.Webpanelb\x06pro" +
	"to3"

var (
	file_app_webpanel_config_proto_rawDescOnce sync.Once
	file_app_webpanel_config_proto_rawDescData []byte
)

func file_app_webpanel_config_proto_rawDescGZIP() []byte {
	file_app_webpanel_config_proto_rawDescOnce.Do(func() {
		file_app_webpanel_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_webpanel_config_proto_rawDesc), len(file_app_webpanel_config_proto_rawDesc)))
	})
	return file_app_webpanel_config_proto_rawDescData
}

var file_app_webpanel_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_webpanel_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.app.webpanel.Config
}
var file_app_webpanel_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_webpanel_config_proto_init() }
func file_app_webpanel_config_proto_init() {
	if File_app_webpanel_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_webpanel_config_proto_rawDesc), len(file_app_webpanel_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_webpanel_config_proto_goTypes,
		DependencyIndexes: file_app_webpanel_config_proto_depIdxs,
		MessageInfos:      file_app_webpanel_config_proto_msgTypes,
	}.Build()
	File_app_webpanel_config_proto = out.File
	file_app_webpanel_config_proto_goTypes = nil
	file_app_webpanel_config_proto_depIdxs = nil
}
